// Code generated by ethgo/abigen. DO NOT EDIT.
// Hash: 1d2c32c0d16460e06edab1ec4f269a1a1eb89530f4ef52bec572829505b88c27
// Version: 0.1.3
package contracts

import (
	"fmt"
	"math/big"

	"github.com/umbracle/ethgo"
	"github.com/umbracle/ethgo/contract"
	"github.com/umbracle/ethgo/jsonrpc"
)

var (
	_ = big.NewInt
	_ = jsonrpc.NewClient
)

// LoadTester is a solidity contract
type LoadTester struct {
	c *contract.Contract
}

// DeployLoadTester deploys a new LoadTester contract
func DeployLoadTester(provider *jsonrpc.Client, from ethgo.Address, args []interface{}, opts ...contract.ContractOption) (contract.Txn, error) {
	return contract.DeployContract(abiLoadTester, binLoadTester, args, opts...)
}

// NewLoadTester creates a new instance of the contract at a specific address
func NewLoadTester(addr ethgo.Address, opts ...contract.ContractOption) *LoadTester {
	return &LoadTester{c: contract.NewContract(addr, abiLoadTester, opts...)}
}

// calls

// GetCallCounter calls the getCallCounter method in the solidity contract
func (l *LoadTester) GetCallCounter(block ...ethgo.BlockNumber) (retval0 *big.Int, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = l.c.Call("getCallCounter", ethgo.EncodeBlock(block...))
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(*big.Int)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	
	return
}

// txns

// Inc sends a inc transaction in the solidity contract
func (l *LoadTester) Inc() (contract.Txn, error) {
	return l.c.Txn("inc")
}

// TestADD sends a testADD transaction in the solidity contract
func (l *LoadTester) TestADD(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testADD", x)
}

// TestADDMOD sends a testADDMOD transaction in the solidity contract
func (l *LoadTester) TestADDMOD(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testADDMOD", x)
}

// TestADDRESS sends a testADDRESS transaction in the solidity contract
func (l *LoadTester) TestADDRESS(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testADDRESS", x)
}

// TestAND sends a testAND transaction in the solidity contract
func (l *LoadTester) TestAND(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testAND", x)
}

// TestBALANCE sends a testBALANCE transaction in the solidity contract
func (l *LoadTester) TestBALANCE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testBALANCE", x)
}

// TestBASEFEE sends a testBASEFEE transaction in the solidity contract
func (l *LoadTester) TestBASEFEE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testBASEFEE", x)
}

// TestBLOCKHASH sends a testBLOCKHASH transaction in the solidity contract
func (l *LoadTester) TestBLOCKHASH(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testBLOCKHASH", x)
}

// TestBYTE sends a testBYTE transaction in the solidity contract
func (l *LoadTester) TestBYTE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testBYTE", x)
}

// TestCALLDATACOPY sends a testCALLDATACOPY transaction in the solidity contract
func (l *LoadTester) TestCALLDATACOPY(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testCALLDATACOPY", x)
}

// TestCALLDATALOAD sends a testCALLDATALOAD transaction in the solidity contract
func (l *LoadTester) TestCALLDATALOAD(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testCALLDATALOAD", x)
}

// TestCALLDATASIZE sends a testCALLDATASIZE transaction in the solidity contract
func (l *LoadTester) TestCALLDATASIZE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testCALLDATASIZE", x)
}

// TestCALLER sends a testCALLER transaction in the solidity contract
func (l *LoadTester) TestCALLER(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testCALLER", x)
}

// TestCALLVALUE sends a testCALLVALUE transaction in the solidity contract
func (l *LoadTester) TestCALLVALUE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testCALLVALUE", x)
}

// TestCHAINID sends a testCHAINID transaction in the solidity contract
func (l *LoadTester) TestCHAINID(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testCHAINID", x)
}

// TestCODECOPY sends a testCODECOPY transaction in the solidity contract
func (l *LoadTester) TestCODECOPY(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testCODECOPY", x)
}

// TestCODESIZE sends a testCODESIZE transaction in the solidity contract
func (l *LoadTester) TestCODESIZE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testCODESIZE", x)
}

// TestCOINBASE sends a testCOINBASE transaction in the solidity contract
func (l *LoadTester) TestCOINBASE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testCOINBASE", x)
}

// TestDIFFICULTY sends a testDIFFICULTY transaction in the solidity contract
func (l *LoadTester) TestDIFFICULTY(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testDIFFICULTY", x)
}

// TestDIV sends a testDIV transaction in the solidity contract
func (l *LoadTester) TestDIV(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testDIV", x)
}

// TestEQ sends a testEQ transaction in the solidity contract
func (l *LoadTester) TestEQ(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testEQ", x)
}

// TestEXP sends a testEXP transaction in the solidity contract
func (l *LoadTester) TestEXP(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testEXP", x)
}

// TestEXTCODESIZE sends a testEXTCODESIZE transaction in the solidity contract
func (l *LoadTester) TestEXTCODESIZE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testEXTCODESIZE", x)
}

// TestGAS sends a testGAS transaction in the solidity contract
func (l *LoadTester) TestGAS(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testGAS", x)
}

// TestGASLIMIT sends a testGASLIMIT transaction in the solidity contract
func (l *LoadTester) TestGASLIMIT(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testGASLIMIT", x)
}

// TestGASPRICE sends a testGASPRICE transaction in the solidity contract
func (l *LoadTester) TestGASPRICE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testGASPRICE", x)
}

// TestGT sends a testGT transaction in the solidity contract
func (l *LoadTester) TestGT(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testGT", x)
}

// TestISZERO sends a testISZERO transaction in the solidity contract
func (l *LoadTester) TestISZERO(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testISZERO", x)
}

// TestLOG0 sends a testLOG0 transaction in the solidity contract
func (l *LoadTester) TestLOG0(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testLOG0", x)
}

// TestLOG1 sends a testLOG1 transaction in the solidity contract
func (l *LoadTester) TestLOG1(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testLOG1", x)
}

// TestLOG2 sends a testLOG2 transaction in the solidity contract
func (l *LoadTester) TestLOG2(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testLOG2", x)
}

// TestLOG3 sends a testLOG3 transaction in the solidity contract
func (l *LoadTester) TestLOG3(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testLOG3", x)
}

// TestLOG4 sends a testLOG4 transaction in the solidity contract
func (l *LoadTester) TestLOG4(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testLOG4", x)
}

// TestLT sends a testLT transaction in the solidity contract
func (l *LoadTester) TestLT(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testLT", x)
}

// TestMLOAD sends a testMLOAD transaction in the solidity contract
func (l *LoadTester) TestMLOAD(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testMLOAD", x)
}

// TestMOD sends a testMOD transaction in the solidity contract
func (l *LoadTester) TestMOD(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testMOD", x)
}

// TestMSIZE sends a testMSIZE transaction in the solidity contract
func (l *LoadTester) TestMSIZE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testMSIZE", x)
}

// TestMSTORE sends a testMSTORE transaction in the solidity contract
func (l *LoadTester) TestMSTORE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testMSTORE", x)
}

// TestMSTORE8 sends a testMSTORE8 transaction in the solidity contract
func (l *LoadTester) TestMSTORE8(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testMSTORE8", x)
}

// TestMUL sends a testMUL transaction in the solidity contract
func (l *LoadTester) TestMUL(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testMUL", x)
}

// TestMULMOD sends a testMULMOD transaction in the solidity contract
func (l *LoadTester) TestMULMOD(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testMULMOD", x)
}

// TestNOT sends a testNOT transaction in the solidity contract
func (l *LoadTester) TestNOT(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testNOT", x)
}

// TestNUMBER sends a testNUMBER transaction in the solidity contract
func (l *LoadTester) TestNUMBER(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testNUMBER", x)
}

// TestOR sends a testOR transaction in the solidity contract
func (l *LoadTester) TestOR(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testOR", x)
}

// TestORIGIN sends a testORIGIN transaction in the solidity contract
func (l *LoadTester) TestORIGIN(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testORIGIN", x)
}

// TestRETURNDATACOPY sends a testRETURNDATACOPY transaction in the solidity contract
func (l *LoadTester) TestRETURNDATACOPY(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testRETURNDATACOPY", x)
}

// TestRETURNDATASIZE sends a testRETURNDATASIZE transaction in the solidity contract
func (l *LoadTester) TestRETURNDATASIZE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testRETURNDATASIZE", x)
}

// TestSAR sends a testSAR transaction in the solidity contract
func (l *LoadTester) TestSAR(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSAR", x)
}

// TestSDIV sends a testSDIV transaction in the solidity contract
func (l *LoadTester) TestSDIV(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSDIV", x)
}

// TestSELFBALANCE sends a testSELFBALANCE transaction in the solidity contract
func (l *LoadTester) TestSELFBALANCE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSELFBALANCE", x)
}

// TestSGT sends a testSGT transaction in the solidity contract
func (l *LoadTester) TestSGT(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSGT", x)
}

// TestSHA3 sends a testSHA3 transaction in the solidity contract
func (l *LoadTester) TestSHA3(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSHA3", x)
}

// TestSHL sends a testSHL transaction in the solidity contract
func (l *LoadTester) TestSHL(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSHL", x)
}

// TestSHR sends a testSHR transaction in the solidity contract
func (l *LoadTester) TestSHR(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSHR", x)
}

// TestSIGNEXTEND sends a testSIGNEXTEND transaction in the solidity contract
func (l *LoadTester) TestSIGNEXTEND(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSIGNEXTEND", x)
}

// TestSLOAD sends a testSLOAD transaction in the solidity contract
func (l *LoadTester) TestSLOAD(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSLOAD", x)
}

// TestSLT sends a testSLT transaction in the solidity contract
func (l *LoadTester) TestSLT(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSLT", x)
}

// TestSMOD sends a testSMOD transaction in the solidity contract
func (l *LoadTester) TestSMOD(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSMOD", x)
}

// TestSSTORE sends a testSSTORE transaction in the solidity contract
func (l *LoadTester) TestSSTORE(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSSTORE", x)
}

// TestSUB sends a testSUB transaction in the solidity contract
func (l *LoadTester) TestSUB(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testSUB", x)
}

// TestTIMESTAMP sends a testTIMESTAMP transaction in the solidity contract
func (l *LoadTester) TestTIMESTAMP(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testTIMESTAMP", x)
}

// TestXOR sends a testXOR transaction in the solidity contract
func (l *LoadTester) TestXOR(x *big.Int) (contract.Txn, error) {
	return l.c.Txn("testXOR", x)
}

// events
